require: rubocop-rspec

inherit_from:
  - http://relaxed.ruby.style/rubocop.yml

AllCops:
  DisplayStyleGuide: true
  DisplayCopNames: true
  TargetRubyVersion: 2.5.3
  Exclude:
    - 'db/schema.rb'
    - 'db/migrate/*'
    - 'vendor/**/*'
    - 'config/environments/*.rb'
    - 'bin/*'

Rails:
  Enabled: true
  Exclude:
    - 'app/models/user.rb'

Rails/Output:
  Enabled: false

Style/DateTime:
  Enabled: true

Metrics/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
    - 'Guardfile'
    - 'vendor/bundle'
